from typing import Any, Optional, Tuple, List, Dict, Literal
from .geometry_kernel_base import GeometryKernelBase

# 定义支持的几何内核名称（示例）
KernelName = Literal["occ"]

class GeometryKernelManager:
    # 属性
    current_kernel_name: KernelName
    available_kernels: Dict[KernelName, GeometryKernelBase]

    # 管理方法
    def __init__(self, default_kernel: Optional[str]=None) -> None: ...
    def load_kernel(self, name: str) -> None: ...
    def set_kernel(self, name: str) -> None: ...
    def get_current_kernel(self, logger_msg=None) -> GeometryKernelBase: ...

    # 代理几何操作（与 GeometryKernelBase 方法一致）
    def create_box(self, width: float, height: float, depth: float) -> Any: ...
    def create_sphere(self, radius: float) -> Any: ...
    def boolean_union(self, shape1: Any, shape2: Any) -> Any: ...
    def transform(self, shape: Any, translation: Tuple[float, float, float], rotation: Tuple[float, ...]) -> Any: ...
    def get_volume(self, shape: Any) -> float: ...
    def get_bounding_box(self, shape: Any) -> Tuple[Tuple[float, ...], Tuple[float, ...]]: ...
    def save_to_file(self, shape: Any, filename: str, format: str="STEP") -> None: ...